### PR TITLE
Removed build script from xee

### LINKED ISSUE #60: Support installation from crates.io
Currently I can't run

```bash
cargo install xee
```

to install `xee` from crates.io. The command fails (rather late in the build, which is extra unfortunate), because the [build script](https://github.com/Paligo/xee/blob/main/xee/build.rs) requires to be executed in a git repository, which is not the case when we download the source tarball from the registry. AFAICT, this is only needed to construct the [version string](https://github.com/Paligo/xee/blob/main/xee/src/main.rs#L11-L16) displayed in the CLI. My personal preference would be if [`build_data`](https://docs.rs/build-data/latest/build_data/) were to offer a non-panicking version of their setter functions, so we could silently omit the info (or replace it with `"crates.io"`, or something). But before I raise an issue with them, I wanted to discuss this here first.

### PR DESCRIPTION
**Pull request by jofas**
Closes #60 by deleting the build script. This removes commit hash and source timestamp from the version string shown in the CLI and REPL.

### CODE REVIEW

File: xee/src/main.rs [hunk 1]
```diff
@@ -1,24 +1,16 @@
+mod common;
 mod error;
 mod format;
 mod indent;
 mod repl;
 mod repl_cmd;
-mod xslt;
 mod xpath;
-mod common;
+mod xslt;
```
Comment (jofas) [inline xee/src/main.rs:8]: Rustfmt orders module declarations and grouped imports from the same crate alphabetically. My editor runs rustfmt automatically when I save a file, which is what happened here. Hope you don't mind the mix of format- and code-related changes in the same commit/PR.

File: xee/src/repl.rs [hunk 2]
```diff
@@ -200,7 +199,7 @@ impl Repl {
             ),
         ]);
 
-        println!("Xee XPath REPL {}", VERSION);
+        println!("Xee XPath REPL {}", clap::crate_version!());
```
Comment (jofas) [inline xee/src/repl.rs:202]: Now that I'm seeing this in the diff, I might've been a bit overeager in removing `VERSION` completely. Maybe a

```rust
pub(crate) const VERSION: &str = clap::crate_version!();
```

would have been better than removing the constant completely and calling `clap::crate_version` inline here.

Comment (jofas) [reply xee/src/repl.rs:202]: Oh, there is! I overlooked that `Repl` derives `Parser`, which allows us to use [`CommandFactory::command`](https://docs.rs/clap/latest/clap/trait.CommandFactory.html#tymethod.command) to retrieve the command and subsequently [`Command::get_version`](https://docs.rs/clap/latest/clap/struct.Command.html#method.get_version) to get the version.

Comment (jofas) [reply xee/src/repl.rs]: I made the change in 93a4c2d. It's a lot better than `crate_version!()`. I'm a bit confused about the layout of clap-related structures though. I thought structs in a `Subcommand` variants could only derive `Args`, not be full blown `Parser`s themselves. Was this a conscious design decision?

Comment (faassen) [reply xee/src/repl.rs]: No, I doubt it was a conscious design decision.

**Review by faassen — APPROVED** [review]
